export default {
  fonts: {
    body:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
  },
  borders: {
    scaffold: `red 1px solid`,
  },
  buttons: {
    success: {
      color: '#fff',
      bg: 'green',
      width: 100,
      height: 20,
      borderRadius: `3px`,
      cursor: `pointer`,
    },
    warning: {
      color: '#fff',
      bg: 'red',
      width: 100,
      height: 20,
      textAlign: 'center',
      borderRadius: `3px`,
      cursor: `pointer`,
    },
    caution: {
      color: '#000',
      bg: 'rgb(252,186,3)',
      width: 100,
      height: 20,
      borderRadius: `3px`,
      cursor: `pointer`,
    },
  },
  lis: {
    success_small: {
      bg: 'green',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
      width: 150,
    },
    success_medium: {
      bg: 'green',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    success_large: {
      bg: 'green',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
    warning_small: {
      bg: 'red',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    warning_medium: {
      bg: 'red',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    warning_large: {
      bg: 'red',
      borderRadius: `3px`,
      color: '#fff',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
    caution_small: {
      bg: 'rgb(252,186,3)',
      borderRadius: `3px`,
      color: '#000',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    caution_medium: {
      bg: 'rgb(252,186,3)',
      borderRadius: `3px`,
      color: '#000',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    caution_large: {
      bg: 'rgb(252,186,3)',
      borderRadius: `3px`,
      color: '#000',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
  },
}
