export default {
  fonts: {
    body:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
    success: 'green',
    successMuted: 'honeydew',
    warning:'red',
    warningMuted: 'lightpink',
    caution: 'rgb(252,186,3)',
    cautionMuted: 'lightyellow'
  },
  borders: {
    scaffold: `red 1px solid`,
  },
  as: {
    brand: {
      color: 'background',
      fontSize: '2rem',
      height: '60px',
      lineHeight: '60px',
      padding: '0 10px',
      textDecoration: 'none',
      width: '150px',
    },
  },
  buttons: {
    information: {
      color: 'background',
      bg: 'primary',
      width: 100,
      height: 20,
      borderRadius: `3px`,
      cursor: `pointer`,
    },
    success: {
      color: 'background',
      bg: 'success',
      width: 100,
      height: 20,
      borderRadius: `3px`,
      cursor: `pointer`,
    },
    warning: {
      color: 'background',
      bg: 'warning',
      width: 100,
      height: 20,
      textAlign: 'center',
      borderRadius: `3px`,
      cursor: `pointer`,
    },
    caution: {
      color: 'text',
      bg: 'caution',
      width: 100,
      height: 20,
      borderRadius: `3px`,
      cursor: `pointer`,
    },
  },
  lis: {
    height:`20px`,
    top_nav: {
      color: 'gray',
      fontSize: '1.25rem',
      height: '60px',
      lineHeight: '60px',
      padding: '0 10px',
      textDecoration: 'none',
      width: '150px',
    },
    primary_small: {
      bg: 'primary',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    success_small: {
      bg: 'success',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    success_medium: {
      bg: 'success',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    success_large: {
      bg: 'success',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
    warning_small: {
      bg: 'warning',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    warning_medium: {
      bg: 'warning',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    warning_large: {
      bg: 'warning',
      borderRadius: `3px`,
      color: 'background',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
    caution_small: {
      bg: 'caution',
      borderRadius: `3px`,
      color: 'text',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 20,
      listStyle: `none`,
      mr: `5px`,
      p: `3px 3px`,
      textAlign: 'center',
      width: 50,
    },
    caution_medium: {
      bg: 'caution',
      borderRadius: `3px`,
      color: 'text',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 150,
    },
    caution_large: {
      bg: 'caution',
      borderRadius: `3px`,
      color: 'text',
      cursor: `pointer`,
      fontSize: `14px`,
      fontWeight: 700,
      height: 24,
      listStyle: `none`,
      mr: `5px`,
      p: `5px 3px`,
      textAlign: 'center',
      width: 250,
    },
  },
}
